"""Shared SQLAlchemy declarative base and session plumbing.

Contract: every persisted model in any context inherits :class:`Base` so
Alembic sees one metadata and constraint names are deterministic (the naming
convention below makes autogenerated migrations reviewable and downgrades
reliable). Sessions are created per unit-of-work by the interface layer;
domain and application code never see SQLAlchemy types.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

from sqlalchemy import CursorResult, MetaData
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase

if TYPE_CHECKING:
    from sqlalchemy.engine import Result
    from sqlalchemy.ext.asyncio import AsyncEngine

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def create_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    return async_sessionmaker(engine, expire_on_commit=False)


def affected_rows(result: Result[Any]) -> int:
    """Row count of a DML statement.

    ``AsyncSession.execute`` is typed as returning ``Result``, but UPDATE/DELETE
    yield a ``CursorResult`` at runtime; ``rowcount`` lives there. This cast is
    the one sanctioned place that bridges the SQLAlchemy typing gap.
    """
    return cast("CursorResult[Any]", result).rowcount
