"""code index: snapshots, indexed files, symbols, chunks

Revision ID: 0029007da215
Revises: f04939ccfed3
Create Date: 2026-07-10 21:50:09.934560

Every migration ships a real, tested downgrade (docs/12 §4).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0029007da215"
down_revision = "f04939ccfed3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("header_path", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("start_byte", sa.BigInteger(), nullable=False),
        sa.Column("end_byte", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_code_chunks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_chunks")),
    )
    op.create_index(
        op.f("ix_code_chunks_workspace_id"), "code_chunks", ["workspace_id"], unique=False
    )
    op.create_index("ix_code_chunks_ws_path", "code_chunks", ["workspace_id", "path"], unique=False)
    op.create_table(
        "index_snapshots",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("symbol_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_index_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_index_snapshots")),
    )
    op.create_table(
        "indexed_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_indexed_files_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indexed_files")),
        sa.UniqueConstraint("workspace_id", "path", name="uq_indexed_files_ws_path"),
    )
    op.create_index(
        op.f("ix_indexed_files_workspace_id"), "indexed_files", ["workspace_id"], unique=False
    )
    op.create_table(
        "symbols",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("qualified_name", sa.String(length=1024), nullable=False),
        sa.Column("parent", sa.String(length=1024), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("start_byte", sa.BigInteger(), nullable=False),
        sa.Column("end_byte", sa.BigInteger(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_symbols_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbols")),
    )
    op.create_index(op.f("ix_symbols_workspace_id"), "symbols", ["workspace_id"], unique=False)
    op.create_index("ix_symbols_ws_name", "symbols", ["workspace_id", "name"], unique=False)
    op.create_index("ix_symbols_ws_path", "symbols", ["workspace_id", "path"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_symbols_ws_path", table_name="symbols")
    op.drop_index("ix_symbols_ws_name", table_name="symbols")
    op.drop_index(op.f("ix_symbols_workspace_id"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(op.f("ix_indexed_files_workspace_id"), table_name="indexed_files")
    op.drop_table("indexed_files")
    op.drop_table("index_snapshots")
    op.drop_index("ix_code_chunks_ws_path", table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_workspace_id"), table_name="code_chunks")
    op.drop_table("code_chunks")
    # ### end Alembic commands ###
